"""解析プラグイン共通インターフェース。"""

from __future__ import annotations

from typing import Protocol
import numpy as np


class AnalyzerPlugin(Protocol):
    """ゲーム画面解析プラグインのプロトコル。"""

    def detect_match_select(self, frame: np.ndarray) -> bool: ...

    def extract_rate(self, frame: np.ndarray) -> int | None: ...

    def detect_matching_start(self, frame: np.ndarray) -> bool: ...

    def detect_schedule_change(self, frame: np.ndarray) -> bool: ...

    def detect_battle_start(self, frame: np.ndarray) -> bool: ...

    def detect_battle_abort(self, frame: np.ndarray) -> bool: ...

    def detect_battle_finish(self, frame: np.ndarray) -> bool: ...

    def detect_battle_finish_end(self, frame: np.ndarray) -> bool: ...

    def detect_battle_judgement(self, frame: np.ndarray) -> bool: ...

    def extract_battle_judgement(self, frame: np.ndarray) -> str | None: ...

    def detect_loading(self, frame: np.ndarray) -> bool: ...

    def detect_loading_end(self, frame: np.ndarray) -> bool: ...

    def detect_battle_result(self, frame: np.ndarray) -> bool: ...

    def extract_battle_result(self, frame: np.ndarray) -> str | None: ...
