from __future__ import annotations

from typing import Any

class Resource:
    def videos(self) -> Resource: ...
    def thumbnails(self) -> Resource: ...
    def captions(self) -> Resource: ...
    def playlistItems(self) -> Resource: ...
    def insert(self, *args: Any, **kwargs: Any) -> Resource: ...
    def set(self, *args: Any, **kwargs: Any) -> Resource: ...
    def execute(self) -> Any: ...

def build(
    serviceName: str, version: str, *, credentials: Any | None = ...
) -> Resource: ...
