"""インフラ層公開API。"""

from . import filesystem, logging

__all__ = [
    "filesystem",
    "logging",
    "MatcherRegistry",
    "CaptureDeviceChecker",
    "CaptureDeviceEnumerator",
    "Capture",
    "NDICapture",
    "OBSRecorderController",
    "RecorderWithTranscription",
    "FFmpegProcessor",
    "YouTubeClient",
    "EventPublisherAdapter",
    "EventBusPortAdapter",
    "FramePublisherAdapter",
    "GuiRuntimePortAdapter",
    "SystemPower",
    "TesseractOCR",
    "SubtitleEditor",
    "ImageDrawer",
    "IntegratedSpeechRecognizer",
    "MicrophoneEnumerator",
    "SpeechTranscriber",
    "GoogleTextToSpeech",
    "FileVideoAssetRepository",
    "SetupStateFileAdapter",
    "SystemCommandAdapter",
    "StructlogLoggerAdapter",
    "TomlConfigAdapter",
    "TomlSettingsRepository",
    "FileSystemPathsAdapter",
    "LocalFileSystemAdapter",
    "ProcessEnvironmentAdapter",
    "WeaponRecognitionAdapter",
]

from .adapters import (
    Capture,
    CaptureDeviceChecker,
    CaptureDeviceEnumerator,
    EventBusPortAdapter,
    EventPublisherAdapter,
    FFmpegProcessor,
    FileSystemPathsAdapter,
    FramePublisherAdapter,
    GoogleTextToSpeech,
    GuiRuntimePortAdapter,
    ImageDrawer,
    IntegratedSpeechRecognizer,
    LocalFileSystemAdapter,
    MicrophoneEnumerator,
    NDICapture,
    OBSRecorderController,
    ProcessEnvironmentAdapter,
    RecorderWithTranscription,
    SetupStateFileAdapter,
    SpeechTranscriber,
    StructlogLoggerAdapter,
    SubtitleEditor,
    SystemCommandAdapter,
    SystemPower,
    TesseractOCR,
    TomlConfigAdapter,
    TomlSettingsRepository,
    WeaponRecognitionAdapter,
    YouTubeClient,
)
from .matchers import MatcherRegistry
from .repositories import FileVideoAssetRepository
