# Minimal mypy stub for webrtcvad used in this project

class Vad:
    def __init__(self, mode: int) -> None: ...
    def set_mode(self, mode: int) -> None: ...
    def is_speech(self, frame_bytes: bytes, sample_rate: int) -> bool: ...
