# 単一手法検出器（シンプルな検出用）
simple_matchers:
  
  virtual_camera_off:
    type: "hash"
    hash_path: "hashes/virtual_camera_off.png"
    threshold: 0.9
    description: "仮想カメラOFFのハッシュ"
    enabled: true

  black_screen:
    type: "brightness"
    max_value: 20
    min_value: null
    description: "電源OFF時の暗さ判定"
    enabled: true

  power_off_template:
    type: "template"
    template_path: "templates/power_off.png"
    threshold: 0.9
    description: "電源OFFテンプレート"
    enabled: true

  matching_start_hsv:
    type: "hsv"
    mask_path: "templates/matching_start.png"
    lower_bound: [0, 0, 200]
    upper_bound: [179, 20, 255]
    threshold: 0.9
    description: "マッチング開始時のHSV"
    enabled: true

  matching_start_template:
    type: "template"
    template_path: "templates/matching_start.png"
    threshold: 0.9
    description: "マッチング開始テンプレート"
    enabled: true

  change_schedule_brightness:
    type: "brightness"
    max_value: null
    min_value: 20
    roi:
      x: 555
      y: 444
      width: 111
      height: 111
    description: "スケジュール変更時の明るさ判定"
    enabled: true

  change_schedule_template:
    type: "template"
    template_path: "templates/change_schedule.png"
    threshold: 0.9
    description: "スケジュール変更テンプレート"
    enabled: true

  battle_start_brightness:
    type: "brightness"
    max_value: null
    min_value: 20
    roi:
      x: 900
      y: 360
      width: 140
      height: 20
    description: "バトル開始時の明るさ判定"
    enabled: true

  battle_start_template:
    type: "template"
    template_path: "templates/battle_start.png"
    threshold: 0.9
    description: "バトル開始テンプレート"
    enabled: true

  battle_abort_hsv:
    type: "hsv"
    roi:
      x: 800
      y: 220
      width: 300
      height: 80
    lower_bound: [0, 0, 25]
    upper_bound: [0, 0, 35]
    threshold: 0.9
    description: "バトル中止時のHSV"
    enabled: true

  battle_abort_template:
    type: "template"
    template_path: "templates/battle_abort.png"
    threshold: 0.9
    description: "バトル中止テンプレート"
    enabled: true

# ゲームモード検出（ルール別）
game_modes:
  # シーン検出と同じ構造で各ゲームモードを定義
  # 例: turf_war, splat_zones, tower_control, rainmaker, clam_blitz

# 複合条件検出（より複雑な条件組み合わせ）
composite_detection:
  power_off:
    success_condition: "any_can_pass"
    matchers:
      - black_screen
      - power_off_template
  
  battle_start:
    success_condition: "all_must_pass"
    matchers:
      - battle_start_brightness
      - battle_start_template
      - 
  matching_start_hsv:
    success_condition: "all_must_pass"
    matchers:
      - matching_start_hsv
      - matching_start_template